name: laravel_starter_kit
recipe: laravel
config:
  webroot: public
  php: '8.1'
services:
  database:
    type: mysql
    portforward: 3307
    creds:
      user: admin
      password: admin
      database: starterkit
